// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztrmoxudskcyqodpzuub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cm1veHVkc2tjeXFvZHB6dXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNzkwNjQsImV4cCI6MjA1MjY1NTA2NH0.znvtvufy2nTHDCwfPNCi2V2t6noBubnR69aRNmsl9Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);